ROLL	= condor
NAME    = roll-$(ROLL)-usersguide
RELEASE = 0
MANUALRELEASE = V7_4_4
SUMMARY_COMPATIBLE	= $(VERSION)
SUMMARY_MAINTAINER	= Rocks Group
SUMMARY_ARCHITECTURE	= i386, x86_64

ROLL_REQUIRES		= base kernel os
ROLL_CONFLICTS		=

